version: '3'

services:
  stream-s3-upload:
    tty: true
    restart: unless-stopped
    image: s3upload:1.0
    depends_on:
      - stream-s3-upload-rpc
    command: [ "make", "file-server-build"]

  stream-s3-upload-rpc:
    tty: true
    restart: unless-stopped
    image: s3upload_rpc:1.0
    ports:
      - '50081:50081'
    command: [ "make", "file-python" ]