# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/filestream.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/filestream.proto',
  package='file_stream',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x16proto/filestream.proto\x12\x0b\x66ile_stream\"R\n\x0binput_frame\x12\x11\n\tfile_name\x18\x01 \x01(\t\x12\x11\n\tfile_type\x18\x02 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x0c\x12\x0f\n\x07user_id\x18\x05 \x01(\t\"x\n\x0coutput_frame\x12\x12\n\nvalid_data\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x11\n\tfile_path\x18\x03 \x01(\t\x12\x14\n\x0c\x66ile_encrypt\x18\x04 \x01(\t\x12\x0c\n\x04rows\x18\x05 \x01(\x03\x12\x0c\n\x04\x63ols\x18\x06 \x01(\x03\x32Y\n\x0cstream_input\x12I\n\x10\x43onvertDataframe\x12\x18.file_stream.input_frame\x1a\x19.file_stream.output_frame\"\x00\x62\x06proto3'
)




_INPUT_FRAME = _descriptor.Descriptor(
  name='input_frame',
  full_name='file_stream.input_frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_name', full_name='file_stream.input_frame.file_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_type', full_name='file_stream.input_frame.file_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='file_stream.input_frame.data', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user_id', full_name='file_stream.input_frame.user_id', index=3,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=121,
)


_OUTPUT_FRAME = _descriptor.Descriptor(
  name='output_frame',
  full_name='file_stream.output_frame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='valid_data', full_name='file_stream.output_frame.valid_data', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='file_stream.output_frame.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_path', full_name='file_stream.output_frame.file_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_encrypt', full_name='file_stream.output_frame.file_encrypt', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='rows', full_name='file_stream.output_frame.rows', index=4,
      number=5, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cols', full_name='file_stream.output_frame.cols', index=5,
      number=6, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=243,
)

DESCRIPTOR.message_types_by_name['input_frame'] = _INPUT_FRAME
DESCRIPTOR.message_types_by_name['output_frame'] = _OUTPUT_FRAME
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

input_frame = _reflection.GeneratedProtocolMessageType('input_frame', (_message.Message,), {
  'DESCRIPTOR' : _INPUT_FRAME,
  '__module__' : 'proto.filestream_pb2'
  # @@protoc_insertion_point(class_scope:file_stream.input_frame)
  })
_sym_db.RegisterMessage(input_frame)

output_frame = _reflection.GeneratedProtocolMessageType('output_frame', (_message.Message,), {
  'DESCRIPTOR' : _OUTPUT_FRAME,
  '__module__' : 'proto.filestream_pb2'
  # @@protoc_insertion_point(class_scope:file_stream.output_frame)
  })
_sym_db.RegisterMessage(output_frame)



_STREAM_INPUT = _descriptor.ServiceDescriptor(
  name='stream_input',
  full_name='file_stream.stream_input',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=245,
  serialized_end=334,
  methods=[
  _descriptor.MethodDescriptor(
    name='ConvertDataframe',
    full_name='file_stream.stream_input.ConvertDataframe',
    index=0,
    containing_service=None,
    input_type=_INPUT_FRAME,
    output_type=_OUTPUT_FRAME,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_STREAM_INPUT)

DESCRIPTOR.services_by_name['stream_input'] = _STREAM_INPUT

# @@protoc_insertion_point(module_scope)
