# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from streamer import filestream_pb2 as proto_dot_filestream__pb2


class stream_inputStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConvertDataframe = channel.unary_unary(
                '/file_stream.stream_input/ConvertDataframe',
                request_serializer=proto_dot_filestream__pb2.input_frame.SerializeToString,
                response_deserializer=proto_dot_filestream__pb2.output_frame.FromString,
                )


class stream_inputServicer(object):
    """Missing associated documentation comment in .proto file"""

    def ConvertDataframe(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_stream_inputServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConvertDataframe': grpc.unary_unary_rpc_method_handler(
                    servicer.ConvertDataframe,
                    request_deserializer=proto_dot_filestream__pb2.input_frame.FromString,
                    response_serializer=proto_dot_filestream__pb2.output_frame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'file_stream.stream_input', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class stream_input(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def ConvertDataframe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/file_stream.stream_input/ConvertDataframe',
            proto_dot_filestream__pb2.input_frame.SerializeToString,
            proto_dot_filestream__pb2.output_frame.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
